services:
  mysql:
    image: mysql:8.4
    container_name: cat_system_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: cat_system
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_0900_ai_ci"
      - "--default-time-zone=+08:00"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

